### ISSUE TITLE
cant decode order from endpoint

### ISSUE THREAD

**Issue by nhtyy** [Uniswap/uniswapx-sdk#79]
tried solidity abi.decode and Order.parse() and both failed,
```solidity
// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.0;
import {Test} from "forge-std/Test.sol";
import {DutchOrder} from "../src/lib/DutchOrderLib.sol";

contract DecodeTest is Test {
    function testDecode() public {
        DutchOrder memory order = abi.decode(
            hex"000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000064b51b750000000000000000000000000000000000000000000000000000000064b51b75000000000000000000000000b507d4ef5ed7a01e37cb578f497329cdb3c273a50000000000000000000000000000000000000000000000000000000000002710000000000000000000000000111111111117dc0aa78b770fa6a738034120c3020000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000e80bf394d190851e215d5f67b67f8f5a52783f1e000000000000000000000000b8bff65b2eeb60d6b37312ca0740a742d5e7f95500000000000000000000000000000000000000000000000000000189635c5eac0000000000000000000000000000000000000000000000000000000064b51b75000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000039a65e493e91140000000000000000000000000000000000000000000000000039a65e493e9114000000000000000000000000b8bff65b2eeb60d6b37312ca0740a742d5e7f955",
            (DutchOrder)
        );
    }
}
```

although DutchOrder.parse() works

albeit this may be user error, 
hash: 0x4568c1ed3ce7d3135c6f424fd9a7ad772e4d8a7eba67ca90265f6e2177dd7311

```javascript
import { parseOrder, Order, OrderValidation } from "@uniswap/uniswapx-sdk";

let order =
  "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000064b51b750000000000000000000000000000000000000000000000000000000064b51b75000000000000000000000000b507d4ef5ed7a01e37cb578f497329cdb3c273a50000000000000000000000000000000000000000000000000000000000002710000000000000000000000000111111111117dc0aa78b770fa6a738034120c3020000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000e80bf394d190851e215d5f67b67f8f5a52783f1e000000000000000000000000b8bff65b2eeb60d6b37312ca0740a742d5e7f95500000000000000000000000000000000000000000000000000000189635c5eac0000000000000000000000000000000000000000000000000000000064b51b75000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000039a65e493e91140000000000000000000000000000000000000000000000000039a65e493e9114000000000000000000000000b8bff65b2eeb60d6b37312ca0740a742d5e7f955";

let parsedOrder: Order = parseOrder(order);
```

```
       throw new errors_1.MissingConfiguration("reactor", reactor);
        ^

MissingConfiguration [Error]: Missing configuration for reactor: 0x0000000000000000000000000000000000000120
    at parseOrder (/Users/nuhhtyy/Work/test/node_modules/@uniswap/uniswapx-sdk/dist/src/order/index.js:25:15)
    at Object.<anonymous> (/Users/nuhhtyy/Work/test/index.js:5:49)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by raster21** [comment]
Getting the same error on a variety of orders, including filled orders such as this one:
```
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000006470cc0c000000000000000000000000000000000000000000000000000000006470cc48000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005283d291dbcf85356a21ba090e6db59121208b4400000000000000000000000000000000000000000000001d7d8b63655a09d79000000000000000000000000000000000000000000000001d7d8b63655a09d7900000000000000000000000000000000000000000000000000000000000000200000000000000000000000000bd7f9d0239f81c94b728d827a87b9864972661ec000000000000000000000000a7152fad7467857dc2d4060fecaadf9f6b8227d3046832f97a5d88fd3896d498631bb6ad7075ca30162566d01013e154bee67e01000000000000000000000000000000000000000000000000000000006470cc48000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000001f9840a85d5af5bf1d1762f925bdaddc4201f984000000000000000000000000000000000000000000000002a4c4736821966241000000000000000000000000000000000000000000000002a16230450cf0830a000000000000000000000000a7152fad7467857dc2d4060fecaadf9f6b8227d3
```

**Comment by raster21** [comment]
@nhtyy how did you fix this error? I am still experiencing it.
`MissingConfiguration [Error]: Missing configuration for reactor: 0x0000000000000000000000000000000000000120`

**Comment by hung-native** [comment]
@nhtyy I am getting the same error. Can you share more about the solution?
