### ISSUE TITLE
MissingConfiguration [Error]: Missing configuration for reactor

### ISSUE THREAD

**Issue by James1847** [Uniswap/uniswapx-sdk#83]
`import {parseOrder, Order, OrderValidation} from '@uniswap/uniswapx-sdk';

const serializedOrder = '0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000064b8deab0000000000000000000000000000000000000000000000000000000064b8dee7000000000000000000000000e348c7959e47646031cea7ed30266a6702d011cc0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000295b163616aa0000000000000000000000000000000000000000000000000000295b163616aa00000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000e80bf394d190851e215d5f67b67f8f5a52783f1e000000000000000000000000a547f747639e32e9742adca278dca8579d812654046832b9ce99e62cdebd3286b7ee2e169c7c9b75b8a2b4a8be172b3f6939d5010000000000000000000000000000000000000000000000000000000064b8def3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000005a98fcbea516cf06857215779fd812ca3bef1b3200000000000000000000000000000000000000000000009234f7af292968000000000000000000000000000000000000000000000000009115643f4f5f20cfdd000000000000000000000000a547f747639e32e9742adca278dca8579d812654';
const order = parseOrder(serializedOrder);

const orderData = order.info;
const orderHash = order.hash();

console.log("orderData: ", orderData, "orderHash: ", orderHash);`

when I'm trying to run the code above, the error occures as below: 
MissingConfiguration [Error]: Missing configuration for reactor: 0x0000000000000000000000000000000000000120

**Comment by shishirhome** [comment]
+1

I am also getting same error:

SerializedData = '0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000064c6316a0000000000000000000000000000000000000000000000000000000064c631ce00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000c7d713b49da000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000006000da47483062a0d734ba3dc7576ce6a0b645c400000000000000000000000093beb904abf2b2e6b640e4a178103454162b303000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064c631ce000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000c7d713b49da0000000000000000000000000000a900c63e2807fa2b3ad3c10fa6c4406424b71fba'

Error:
**MissingConfiguration [Error]: Missing configuration for reactor: 0x0000000000000000000000000000000000000120
    at parseOrder (/Users/AK/Desktop/Crypto2/node_modules/@uniswap/uniswapx-sdk/dist/src/order/index.js:25:15)
    at init (/Users/AK/Desktop/Crypto2/17-UniX/uniswapx/2-sdk.js:49:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)**

**Comment by kushagra2jindal** [comment]
+1 

`MissingConfiguration [Error]: Missing configuration for reactor: 0x0000000000000000000000000000000000000120
    at parseOrder (/Users/kushagra/node_modules/@uniswap/uniswapx-sdk/dist/src/order/index.js:25:15)
    at /Users/kushagra/Desktop/KushagraJindal/Integraate-Projects/uniswapX_tutorial/uniswapXTypeScript/dist/index.js:86:53
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kushagra/Desktop/KushagraJindal/Integraate-Projects/uniswapX_tutorial/uniswapXTypeScript/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by kushagra2jindal** [comment]
Although when I tried the following, it is working perfectly, and I was able to parse the order:- 

`DutchOrder.parse(serialisedOrder, 1)`
